### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by AuroreM** [iampueroo/github-autosuggest#1]
Hey @iampueroo,

I want to use your package but there is no explanation on how to install it.
Would it be possible for you to provide some ? :)

Have a great day !

**Comment by iampueroo** [comment]
Thanks for submitting the issue, @AuroreM! 

You can now find the (current) installation instructions [here](https://github.com/iampueroo/github-autosuggest#installing). (Apologies in advance if you see some issues, still in beta).

Happy holidays!

**Comment by AuroreM** [comment]
Great, thanks :) 
I will use it, and if I'm finding some bugs and if I know how to fix them, I will submit some PR !

(and Happy New Year :))

**Comment by iampueroo** [comment]
@AuroreM out of curiosity, did you download it and have you used it much? Any opinions on it?
